//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Web.UI.WebControls;

namespace Garage_UI
{


    public partial class ListarEventos
    {
        protected Label lblMensaje;
        protected GridView gvEventos;
    }
}
